### ISSUE TITLE
Пример файлика dgissdk.key

### ISSUE THREAD

**Issue by IvanLotoff** [2gis/mobile-sdk-android-demo#170]
Коллеги привет! Хочу интегрировать ваши карты. Мне менеджер выслал ключи для карт и навигации, но мне не прислали файл dgissdk. Можете выложить пример этого файла в assets, чтобы я просто понимал его внешний вид.

**Comment by lagner** [comment]
Приветствую!
Интересно кто из менеджеров прислал тебе такие ключи т.к. он определенно делает что-то не то.

Обычные строки в качестве ключей использовались в старых версиях SDK и больше они не актуальны. `dgissdk` это специально сгенерированный файл, он имеет цифровую подпись и собрать самостоятельно его не получится.
В первую очередь сейчас стоит написать на api@2gis.com(либо курирующему менеджеру) и попросить прислать файл с ключом для мобильного SDK. Заранее можно приготовить android application id т.к. он будет необходим

**Comment by lagner** [comment]
@IvanLotoff с ключом все получилось?

**Comment by IvanLotoff** [comment]
Я поискал на гите другие примеры и нашёл, как в build.gradle прокидываются эти ключи. Я понимаю, что это не секьюрно, потому что нет привязки к пакету, но в целом на период тестированря норм. Потом, как приложение будет готово, напишу по почте, что вы дали.

**Comment by lagner** [comment]
Дело не в секьюрности. Если работают старые ключи, значит у тебя старая версия SDK, которая уже не поддерживается. Использовать ее в новых проектах очень плохая идея.
