### ISSUE TITLE
Не запускается экран навигатора

### ISSUE THREAD

**Issue by flyingdream-500** [2gis/mobile-sdk-android-demo#171]
Здравствуйте!
При попытке открытия экрана навигатора крашится приложение.
Примечательны вот эти строки в логе:
Failed to create OnlineTrafficRouterTag: Failed to resolve OldKeyTag
Failed to create HybridTrafficRouterTag: Failed to resolve OnlineTrafficRouterTag
Полный файл лога прикладываю.
Заранее спасибо!
[Error.txt](https://github.com/2gis/mobile-sdk-android-demo/files/9867318/Error.txt)

**Comment by lagner** [comment]
Добрый день. 
Дело в ключе для SDK. Обратитесь за поддержкой навигатора в вашем ключе к своему менеджеру.  После инициализации с правильным ключом, навигатор заработает.

**Comment by flyingdream-500** [comment]
Благодарю за ответ!
