### ISSUE TITLE
Unable to download maven

### ISSUE THREAD

**Issue by 1encore** [2gis/mobile-sdk-android-demo#172]
`https://artifactory.2gis.dev/sdk-maven-release` throws 504 status code while building the app

**Comment by lagner** [comment]
Hi!

I built the app a minute ago and everything worked fine. The repository had been cloned from scratch.
According to our monitoring maven backend works fine as well. 

So we need more information to help you. Otherwise, I see the case is not reproducible

**Comment by 1encore** [comment]
seems like problem solved by itself
