### ISSUE TITLE
Как можно привязать камеру к текущей геопозиции?

### ISSUE THREAD

**Issue by 1encore** [2gis/mobile-sdk-android-demo#173]
Попробовал сделать таким образом
```
val followController = PlatformLocationFollowController(map)
map.camera.addFollowController(followController)
```

безуспешно, можете меня поправить или скинуть пример? Не нашел в документации

**Comment by maxal9999** [comment]
Нужно еще добавить
myLocationSource = MyLocationMapObjectSource(sdkContext,
                MyLocationDirectionBehaviour.FOLLOW_SATELLITE_HEADING)

map.addSource(myLocationSource)

**Comment by maxal9999** [comment]
https://docs.2gis.com/ru/android/sdk/examples/map#nav-lvl1--Моё_местоположение

Еще вот советую посмотреть
https://docs.2gis.com/ru/android/sdk/reference/4.5/ru.dgis.sdk.map.CameraBehaviour

**Comment by AlexSuvorov2k** [comment]
Если прямо, то примерно так:
```
val followPositionMode = if(enabled) FollowPosition(FollowBearing.ON) else null
val cameraBehaviour = CameraBehaviour(followPositionMode, FollowTilt.OFF)
map.camera.setBehaviour(cameraBehaviour)
```
