### ISSUE TITLE
DarkMode Setting

### ISSUE THREAD

**Issue by luwei1991** [2gis/mobile-sdk-android-demo#176]
how to set dark mode，in this demo，i can see 【attributes_menu】files have dark but No implementation method

**Comment by mariarti91** [comment]
Hello!
May be it is too late, but this SDK use system '[dark mode](https://developer.android.com/develop/ui/views/theming/darktheme)' property. 
And each style file has two themes. For example "day" and "night". This names should be provided to map by [setTheme](https://docs.2gis.com/ru/android/sdk/reference/7.0/ru.dgis.sdk.map.MapView#nav-lvl1--setTheme) method. 
When you turn on 'dark mode' dark theme will be selected.
You can create you own style using https://styles.2gis.com tool.
