### ISSUE TITLE
Оффлайн подгрузка карты

### ISSUE THREAD

**Issue by 1encore** [2gis/mobile-sdk-android-demo#193]
Можно пример кода или проект где есть подругзка карты с оффлайн источника?

**Comment by lagner** [comment]
Для работы c offline данными необходимо использовать [TerritoryManager](https://docs.2gis.com/ru/android/sdk/reference/7.0/ru.dgis.sdk.update.TerritoryManager). Через него ты можешь выбрать и скачать необходимые данные на девайс. Дальше практически все сценарии заработают автоматически в гибридном режиме. Т.е. SDK будет проверять есть ли интернет и более свежие данные и если нет, использовать offline пакет.

Обрати внимание, чтобы работать с offline тебе необходимо иметь Full версию SDK и специальный ключ. Обычные демо ключи не имеют доступа к offline данным.

**Comment by maxal9999** [comment]
Привет сделаем.
