### ISSUE TITLE
Animate marker in map

### ISSUE THREAD

**Issue by PavlenkoEgor311** [2gis/mobile-sdk-android-demo#197]
Добрый день, подскажите пожалуйста, есть ли поддержка установки анимации на маркер, с указанием параметра, что анимация должна проигрываться бесконечно (если использую установку иконки через LottieJSON, то анимация проигрывается один раз)?

**Comment by lagner** [comment]
Привет. 
Бесконечные анимации выйдут в следующем релизе SDK `7.4.0`. На данный момент так сделать нельзя

**Comment by PavlenkoEgor311** [comment]
Здравствуйте, подскажите, пожалуйста 

Кластер состоит из объектов людей на карте у каждого объекта есть личная фотография.
Когда эти объекты собираются в кластер, изображение кластера должно меняться раз в секунду на фотографию входящего в него объекта. И так по кругу.

Просмотрел документацию и тестовый проект, но не нашел способа реализовать подобное.
Буду очень благодарен за ответ.

**Comment by maxal9999** [comment]
Ответил в другой теме.
