### ISSUE TITLE
Маркер геолокации не отображается, если инициализировать Context вне Application

### ISSUE THREAD

**Issue by eldarovich99** [2gis/mobile-sdk-android-demo#198]
Если вызывать DGis.initialize(requireActivity().applicationContext) из фрагмента, то маркер геолокации не отображается

**Comment by lagner** [comment]
Это не на столько связанные вещи. Полагаю что-то косвенное влияет на такое поведение в коде приложения. Нужно пару уточнений
- есть ли при этом какие-то ошибки в логе?
- проверяется пермиссия на получение геопозиции?
- можешь сделать простой пример где это воспроизведется?
