### ISSUE TITLE
Нужна возможность управлять ночным режимом

### ISSUE THREAD

**Issue by eldarovich99** [2gis/mobile-sdk-android-demo#199]
При переключении темы на устройстве автоматически переключается тема карты. 
Есть ли возможность изменить это поведение? В документации про это ничего не указано

**Comment by lagner** [comment]
Привет. 

При создании карты туда передается объект MapOptions. У него есть метод [setTheme](https://docs.2gis.com/ru/android/sdk/reference/7.0/ru.dgis.sdk.map.MapOptions#nav-lvl1--setTheme). 
Если в него передать 2 аргумента, то они будут использоваться как имена светлой и темной темы, в зависимости от темы на устройстве (это поведение по умолчанию). 
Если передать 1 аргумент, то тема будет использоваться всегда одна.

Имена тем задаются в редакторе стилей, если они кастомные. В стилях по умолчанию это _"day", "night"_. 
Например
```kotlin
val mapOptions = MapOptions().apply {
    setTheme("day")
}
val mapView = MapView(this, mapOptions)
```
При таком создании карты, тема будет всегда светлая и не переключаться автоматически

**Comment by eldarovich99** [comment]
Спасибо!
