### ISSUE TITLE
Animate in cluster

### ISSUE THREAD

**Issue by PavlenkoEgor311** [2gis/mobile-sdk-android-demo#201]
Здравствуйте, подскажите, пожалуйста
Кластер состоит из объектов людей на карте у каждого объекта есть личная фотография.
Когда эти объекты собираются в кластер, изображение кластера должно меняться раз в секунду на фотографию входящего в него объекта. И так по кругу.
К сожалению, не нашел способа реализовать подобное.
Буду очень благодарен за ответ.

**Comment by maxal9999** [comment]
Привет. Мы тут по iOS части обсуждали
https://github.com/2gis/mobile-sdk-ios-demo/issues/201
Там пришли к какому то решению, но недостаточно. Прочитайте, пожалуйста, там переписку. Если чего то недостаточно для реализации, то готовы доработать.
