### ISSUE TITLE
Can't update to full version

### ISSUE THREAD

**Issue by AlexSuvorov2k** [2gis/mobile-sdk-android-demo#206]
After updating from version 'ru.dgis.sdk:sdk-map:7.4.0' to 'ru.dgis.sdk:sdk-full:10.1.0' I cannot call method:

`MyMapFragment() : Fragment(){
  override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
    val view = inflater.inflate(R.layout.fragment_twogis_map, null)
    val mapView: MapView = view.mapView as MapView
    mapView.getMapAsync{
    ...
    }
    return view
}`

Error is:
_Cannot access 'androidx.lifecycle.FullLifecycleObserver' which is a supertype of 'ru.dgis.sdk.map.MapView'. Check your module classpath for missing or conflicting dependencies_

Also while trying to run application i getting this:
`pp:mergeExtDexDebug FAILED
AGPBI: {"kind":"warning","text":"One or more classes has class file version >= 56 which is not officially supported.","sources":[{"file":"...\.gradle\\caches\\transforms-3\\bc65c6351d67c75323956ee857426be0\\transformed\\jetified-sdk-full-10.1.0-runtime.jar"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.nc: Sealed classes are not supported as program classes","sources":[{"file":"....\.gradle\\caches\\transforms-3\\bc65c6351d67c75323956ee857426be0\\transformed\\jetified-sdk-full-10.1.0-runtime.jar"}],"tool":"D8"}`

How to fix that?

**Comment by Sameri11** [comment]
Hi! Which version of agp is used in your project? Actually, complete android-related configuration of your project (agp, build tools version, compileOptions, etc) would help us investigate this issue.

**Comment by AlexSuvorov2k** [comment]
> complete android-related configuration

project gradle
https://pastebin.com/QTk75zEB

build.gradle
https://pastebin.com/D2Edmhe5

**Comment by AlexSuvorov2k** [comment]
Fixed by:
- adding classpath:
classpath "com.android.tools:r8:8.2.42"
- change of jdk to 17.0.9
