### ISSUE TITLE
Анимация появления маркера

### ISSUE THREAD

**Issue by IlyaKubyskin** [2gis/mobile-sdk-android-demo#208]
Добрый день. Использую карту с кластеризацией. Нужна fade-анимация для маркеров при разворачивании кластера (как мне сказали, в iOS версии SDK это так работает). Пробовал выставлять animatedAppearance = true для маркера и для кластера, видимых изменений нету.  Есть ли в Android SDK такая возможность в принципе? Если есть, то в чем может быть проблема?

**Comment by Sameri11** [comment]
Привет!
Анимация для кластеров в Android SDK поддержана.
`animatedAppearance` по дефолту уже выставлен в true, если MapObjectManager создается более-менее стандартно. Например: 
```kotlin
    private val clusterRenderer = object : SimpleClusterRenderer {
        override fun renderCluster(cluster: SimpleClusterObject): SimpleClusterOptions {
            return SimpleClusterOptions(...)
        }
    }

    val objectsManager = MapObjectManager.withClustering(map, LogicalPixel(...), Zoom(...), clusterRenderer)
```

То есть, в любом случае нужно создать `SimpleClusterRenderer`, который вернет `SimpleClusterOptions`, и если там не менять `animatedAppearance`, то анимация будет включена.

Если это не так, то нам понадобится информация для дебага на своей стороне:

- Версия SDK (а также вариант, map или full)
- версия Android, если она специфична для воспроизведения
- Данные о девайсе/эмуляторе, если специфично для воспроизведения
- Пример кода, как создается и используется `MapObjectManager` в вашем проекте

**Comment by IlyaKubyskin** [comment]
1. SDK ru.dgis.sdk:sdk-map версия 10.1.0
2. Android 14
3. Проверялось на эмуляторе и на реальном девайсе, так что значения не имеет.
4.
Создание кластеров:
```
private val clusterRenderer = object : SimpleClusterRenderer {
        override fun renderCluster(cluster: SimpleClusterObject): SimpleClusterOptions {
            val objectCount = cluster.objectCount
            return SimpleClusterOptions(
                icon = imageFromBitmap(dGisContext, getClusterIcon(objectCount.toString())),
                iconWidth = LogicalPixel(30.0f),
                animatedAppearance = true
            )
        }
    }
```

Создание менеджера
```
mapObjectManager = MapObjectManager.withClustering(
            map = map,
            logicalPixel = LogicalPixel(60.0f),
            maxZoom = Zoom(18.0f),
            clusterRenderer = clusterRenderer
        )
closeables.add(mapObjectManager)
```

Добавляю маркеры после ответа сервера
```
val markersWithIcons = markers.map {
            val markerIcon = imageFromResource(dGisContext, R.drawable.ic_map_marker)
            Marker(
                MarkerOptions(
                    icon = markerIcon,
                    anchor = Anchor(INFO_ANCHOR_X_DEFAULT, 0f),
                    position = GeoPointWithElevation(
                        latitude = it.markerPosition.latitude,
                        longitude = it.markerPosition.longitude
                    ),
                    userData = OnMarkerClickListener(
                        customMarker = it,
                        onClick = onMarkerClick
                    ),
                    animatedAppearance = true
                )
            )
        }

mapObjectManager.addObjects(markersWithIcons)
```

**Comment by Sameri11** [comment]
Привет снова! Код выглядит так, что анимации должны быть, поэтому мы пока разбираемся. Можно еще попросить скринкаст небольшой того, как это выглядит в приложении?

**Comment by IlyaKubyskin** [comment]
https://github.com/2gis/mobile-sdk-android-demo/assets/35036731/0032eb5e-f0f6-4baf-973d-7df1b43da1bf

Привет, держите.

**Comment by maxal9999** [comment]
Привет. Мы у себя повторить так и не смогли твой кейс. Сделай, пожалуйста, в отдельной ветке нашего демо пример, где стабильно повторяется.

**Comment by maxal9999** [comment]
Понял, спасибо, взяли в работу, в ближайшее время посмотрим.

**Comment by IlyaKubyskin** [comment]
https://github.com/2gis/mobile-sdk-android-demo/assets/35036731/82edec1c-0df8-48da-9d17-9e7e23d1243e

прикреплю видео из iOS версии, примерно такое от меня хотят увидеть в приложении.

**Comment by IlyaKubyskin** [comment]
привет еще раз, удалось воспроизхвести?

**Comment by maxal9999** [comment]
Привет. Да, запланировали работы.

**Comment by maxal9999** [comment]
Привет. Это починил в 12 версии.

**Comment by IlyaKubyskin** [comment]
Спасибо
