### ISSUE TITLE
FATAL EXCEPTION. List has more than one element. Инициализация Navigation View.

### ISSUE THREAD

**Issue by dchugunoff** [2gis/mobile-sdk-android-demo#215]
Столкнулись с проблемой, крашит приложение при переходе с фрагмента, на котором есть NavigationView, и обратно.
https://pastebin.com/JRem1Tzq
![image (3)](https://github.com/2gis/mobile-sdk-android-demo/assets/122897044/5baa2565-5713-4215-8b7d-2e2d705fe0af)
Код, ненужное вырезал.
https://pastebin.com/e9r9CuJA
https://pastebin.com/2AN7BBSu
https://pastebin.com/JiVdg8DR

**Comment by timplifier** [comment]
Окей, каким образом тогда получать текущее местоположение и отображать его, если не добавлять MyLocationMapObjectSource ? Решение с маркером такое себе так как постоянно его перерисовывать это ужас.

К тому же, как я могу подключиться к DefaultLocationSource и получать локацию оттуда ? У вас ведь под капотом все уже реализовано и казалось бы, для чего писать свое получение локации руками, если можно взять из сдк, ведь на этом он весь и строится. 

Более того, как я могу проверять активен ли NavigationManager ? 

И могу ли я включить тмпо lite версию карты без цветов и всяких декоративных элементов для большей производительности ? Так как при старте навигации по маршруту начинает нереально лагать

**Comment by Sameri11** [comment]
Привет! NavigationView сама добавит MyLocationMapObjectSource если поймет, что его сейчас нигде нет. Баг в логике у нас как раз связан с этим, что она не совсем правильно понимает. То есть, вы уберете добавление его руками и все останется примерно как было – маркер будет рисоваться, перелет к местоположению будет работать. Подключаться руками к DefaultLocationSource тоже не будет необходимости.

> как я могу проверять активен ли NavigationManager ?

Не совсем понимаю, что это значит в текущем контексте. Можно чуть более развернуто описать, что хочется проверять?

> И могу ли я включить тмпо lite версию карты без цветов и всяких декоративных элементов для большей производительности ? Так как при старте навигации по маршруту начинает нереально лагать

Lite версия карты не предусмотрена. Тут бы помогло видео с комментами, в какой момент что-то идет не так и хотелось бы это поправить – тогда можем попробовать что-то предметно советовать.

**Comment by timplifier** [comment]
Выпилили добавление руками MyLocationMapObjectSource, даем navigationManager'y navigationManager и не видно маркера с локацией

```
if (!viewModel.navigationState) {
            viewModel.navigationState = true
        }
        binding.navigationView.navigationManager = navigationManager
```
        
```
private val navigationManager by lazy {
        NavigationManager(dgisSdkContext)
    }
```

**Comment by dchugunoff** [comment]
Так же не работает навигация если убрать MyLocationMapObjectSource. Просто висит вью "Потерян сигнал GPS". 
При переходе между экранами и при возвращении на фрагмент с картой - карта улетает непонятно куда.

**Comment by Sameri11** [comment]
Привет! Поняли, будем фиксить баг в ближайший хотфикс-релиз.

**Comment by maxal9999** [comment]
Привет. Починили в 10.4.0. Проверяйте.

**Comment by dchugunoff** [comment]
Извиняюсь за долгий ответ. Все работает отлично!
