### ISSUE TITLE
Не работает смена позиции у маркеров, которые должны кластеризироваться 

### ISSUE THREAD

**Issue by PavlenkoEgor311** [2gis/mobile-sdk-android-demo#217]
Добрый день, столкнулся со следующей проблемой. После перехода на версию 10.5.0 не работает смена позиции у кластеризируемых маркеров (у обычных маркеров данной проблемы не наблюдается). Смена позиции осуществляется только после клика на маркер.

При этом, в версии 7.4.0 позиция менялась, но был баг с тем, что при зуме карты, маркер возвращался в исходную позицию.

Смена позиции осуществляется через 
marker.position = GeoPointWithElevation(latitude, longitude)
marker.zIndex = ZIndex(4)

Подскажите, как исправить подобное поведение?

**Comment by maxal9999** [comment]
Привет. Проверим.

**Comment by maxal9999** [comment]
@PavlenkoEgor311 Привет. Мы проверили, и на наших примерах работает. Сделай, пожалуйста, ветку от нашего депо с примером, где ошибка стабильно повторяется.

**Comment by PavlenkoEgor311** [comment]
@maxal9999 Добрый день. Прикрепляю ссылку на форк https://github.com/PavlenkoEgor311/mobile-sdk-android-demo а так же видео с примером. 
[issue217.zip](https://github.com/user-attachments/files/16245532/issue217.zip)
Буду крайне благодарен ответ и помощь

**Comment by maxal9999** [comment]
Починили в версии 10.6.0
