### ISSUE TITLE
Передача и отображение построенного маршрута.

### ISSUE THREAD

**Issue by dchugunoff** [2gis/mobile-sdk-android-demo#218]
Здравствуйте. 
Подскажите пожалуйста, есть ли возможность в СДК передавать построенный маршрут с одного клиента на другой через внутренний бек нашего сервиса, чтобы не строить его заново.
И есть ли возможность сделать маркер движущегося автомобиля по маршруту?
Нужно это для приложений пассажиров и таксистов.
Чтобы строился 1 и тот же маршрут и пассажир мог видеть где едет водитель.

**Comment by maxal9999** [comment]
Добрый день. По первому вопросу - лучше обратиться в нашу тех поддержку [api@2gis.ru](mailto:api@2gis.ru).
Сейчас есть возможность сериализовать/десериализовать маршрут.
https://docs.2gis.com/ru/android/sdk/reference/10.5/ru.dgis.sdk.navigation.PackedNavigationState

>И есть ли возможность сделать маркер движущегося автомобиля по маршруту?

Есть прям демо пример.
https://github.com/2gis/mobile-sdk-android-demo/blob/master/app/src/main/java/ru/dgis/sdk/demo/SimulateNavigationActivity.kt
