### ISSUE TITLE
Параметр маркера isVisible, как с ним работать?

### ISSUE THREAD

**Issue by KaNcHeR** [2gis/mobile-sdk-android-demo#220]
Инициализирую часть маркеров (и для теста все маркеры) с параметром isVisible = false, но они все равно видимые на карте. Меняю в динамике isVisible на false, и так же они все равно видимые. Например если работать с параметром icon, то работает и в инициализации и в динамике, то есть я делаю null для тех маркеров что должны быть невидимые, но при таком хаке они все равно участвуют в кластеризации.
Версия 10.5.0 - 10.6.0

**Comment by maxal9999** [comment]
Лучше юзать
https://docs.2gis.com/ru/android/sdk/reference/12.0/ru.dgis.sdk.map.MapObjectManager#nav-lvl1--var%20isVisible
