### ISSUE TITLE
TerritoryManager, DgisSourceWorkingMode что с ними делать?

### ISSUE THREAD

**Issue by 1encore** [2gis/mobile-sdk-android-demo#227]
- как карта поймет что текущая территория где пользователь стоит уже загружен и что надо тянуть с него данные о карте?
- есть еще `DgisSourceWorkingMode`, который можно положить по сути на все source-ы, получается я могу положить его в `RouteMapObjectSource` что мне это даст если я поставлю `DgisSourceWorkingMode.OFFLINE`?
- как мне применить territoryManager и `DgisSourceWorkingMode.OFFLINE` для сокращение запросов на ваш сервер?

**Comment by maxal9999** [comment]
Нет, DgisSourceWorkingMode влияет только на DgisSource . RouteMapObjectSource всегда работает в гибридном режиме, так как для корректного маршрута часто нужны онлайн данные. Офлайн маршруты обычно мало кому интересны - чисто как временный маршрут, пока сеть не появится.
