### ISSUE TITLE
Карта выходит за границы view при нахождении внутри NestedScrollView

### ISSUE THREAD

**Issue by AlexSuvorov2k** [2gis/mobile-sdk-android-demo#232]
View с картой находится внутри NestedScrollView в BottomSheetDialogFragment
При попытке скролла карта вылазит за границы контейнера:
![screen](https://github.com/user-attachments/assets/6d2556d3-e38a-438f-ba44-0600fcf09cfa)

Разметка:
```
<androidx.cardview.widget.CardView ...>

        <androidx.core.widget.NestedScrollView...>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical">

                    <FrameLayout
                        android:id="@+id/map"
                        android:layout_width="match_parent"
                        android:layout_height="250dp" ... />
```

У карт-конкурентов есть флаг _movable="true" / "false"_ для обработки такой ситуации.
Подскажите, как можно исправить этот момент?

**Comment by Sameri11** [comment]
Привет! Попробуйте указать `renderMode` для вьюхи-карты, примерно так:
```xml
<ru.dgis.sdk.map.MapView
    android:layout_width="..."
    android:layout_height="..."
    app:dgis_renderMode="texture" />
```

**Comment by AlexSuvorov2k** [comment]
> указать `renderMode`

Работает! Можно ли сделать это программно?

**Comment by AlexSuvorov2k** [comment]
Не смог найти чем отличаются типы рендеринга..
Программно сделал так:
```
        val renderMode = if(liteMode) {
            MapRenderMode.TEXTURE
        } else MapRenderMode.SURFACE

        val mapOptions = MapOptions()
        mapOptions.renderMode = renderMode

        val mapView = MapView(requireContext(), mapOptions)
```

Спасибо!

**Comment by Sameri11** [comment]
Вкратце про отличия: `surface` более оптимизирован и лучше адаптирован к частоте обновления дисплея, например. При этом, его не получается clip'ать, поэтому когда это нужно (например, сделать карту круглой, если в дополнение к вашему кейсу), приходится использовать texture.

Путь через `MapOptions` при создании из кода тоже верный. 

Удачи!
